version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8011:80"
    volumes:
      - ./www:/var/www/html/project
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log/nginx:/var/log/nginx
    links:
      - php
    networks:
      - webnet
  php7.4: # 添加自己构建的php镜像
    image: 875272038/php-workerman:v2.0
    container_name: php
    ports:
      - "9503:9503"
    volumes:
      - ./www:/var/www/html/project
      - ./php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    links:
      - redis
    stdin_open: true
    tty: true
    networks:
      - webnet
  mysql: # 添加mysql服务
    image: mysql:latest
    container_name: mysql
    ports:
      - "3308:3306"
    environment:
      - TZ=Asia/Shanghai # 设置时区
      - MYSQL_ROOT_PASSWORD=root # 设置 root 用户密码 
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 设置编码
    networks:
      - webnet
  redis: # 添加redis服务器
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    ports:
      - "6389:6379"
    networks:
      - webnet
networks:
  webnet:
    driver: bridge
